name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'README.md'
    - analysis_options.yaml
    - 'docs/**'
    - 'extras/**'
    - '.vscode/**'
    - '.gitignore'
    - '.gitattributes'
    - '.editorconfig'

jobs:
  #
  # Build for Android
  #
  build_android:
    runs-on: ubuntu-latest
    #runs-on: [self-hosted, linux, x64]
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2

    - name: Build the project
      run: cmake .
